CREATE TABLE PERSON ( 
 ID INT NOT NULL AUTO_INCREMENT 
 , FIRST_NAME VARCHAR(60) 
 , LAST_NAME VARCHAR(60) 
 , USERNAME VARCHAR(60) NOT NULL
 , PASSWORD VARCHAR(60) NOT NULL 
 , PRIMARY KEY (ID) 
); 
 
CREATE TABLE ACCOUNT ( 
 ID INT NOT NULL AUTO_INCREMENT 
 , OWNER_ID INT NOT NULL 
 , ACCOUNT_NUMBER VARCHAR(60) NOT NULL
 , CAPITAL INT NOT NULL DEFAULT 0 
 , OPENED_DATE DATE 
 , VERSION INT NOT NULL DEFAULT 0 
 , PRIMARY KEY (ID) 
 , CONSTRAINT FK_PERSON FOREIGN KEY (OWNER_ID) 
 REFERENCES PERSON (ID) 
); 

CREATE TABLE TRANSACTION ( 
 ID INT NOT NULL AUTO_INCREMENT 
 , FROM_ACCOUNT_ID INT NOT NULL 
 , TO_ACCOUNT_ID INT NOT NULL 
 , AMOUNT INT NOT NULL
 , TRANSACTION_DATE DATE 
 , VERSION INT NOT NULL DEFAULT 0 
 , PRIMARY KEY (ID) 
 , CONSTRAINT FK_FROM_ACCOUNT FOREIGN KEY (FROM_ACCOUNT_ID) 
 REFERENCES ACCOUNT (ID) 
 , CONSTRAINT FK_TO_ACCOUNT FOREIGN KEY (TO_ACCOUNT_ID) 
 REFERENCES ACCOUNT (ID) 
); 
