INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD) VALUES (0, 'Boris', 'Todorov', 'btodorov', '123');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD) VALUES (1, 'Cris', 'Bokkers', 'cb', '123');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD) VALUES (2, 'Jon', 'Some', 'js', '123');

INSERT INTO ACCOUNT (ID, ACCOUNT_NUMBER, OWNER_ID, CAPITAL, OPENED_DATE) VALUES (0, 'btodorov1', 0, 100, '2014-06-07');
INSERT INTO ACCOUNT (ID, ACCOUNT_NUMBER, OWNER_ID, CAPITAL, OPENED_DATE) VALUES (1, 'btodorov2', 0, 120, '2014-06-06');

INSERT INTO ACCOUNT (ID, ACCOUNT_NUMBER, OWNER_ID, OPENED_DATE) VALUES (2, 'cris1', 1, '2014-06-08');

INSERT INTO ACCOUNT (ID, ACCOUNT_NUMBER, OWNER_ID, OPENED_DATE) VALUES (3, 'jon1', 2, '2014-06-08');

INSERT INTO TRANSACTION (FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, TRANSACTION_DATE)
	VALUES (0, 1, 20, '2014-06-07');
	
INSERT INTO TRANSACTION (FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, TRANSACTION_DATE)
	VALUES (0, 2, 20, '2014-06-08');
	
INSERT INTO TRANSACTION (FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, TRANSACTION_DATE)
	VALUES (3, 1, 20, '2014-06-09');
	
	
INSERT INTO TRANSACTION (FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, TRANSACTION_DATE)
	VALUES (2, 3, 20, '2014-06-09');